In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3])
print(array)

[1 2 3]


In [3]:
array.shape

(3,)

In [7]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
array2.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [8]:
array2.ndim

1

In [9]:
array.dtype.name

'int32'

In [10]:
array2.size

15

In [11]:
type(array2)

numpy.ndarray

In [13]:
array3 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
array3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [15]:
zeros = np.zeros((5,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
ones = np.ones((2,2))
ones

array([[1., 1.],
       [1., 1.]])

In [17]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.17780797e-321],
       [1.02451580e-259, 2.25563595e-153, 3.74168445e+233]])

In [18]:
np.arange(10,20,0.2)

array([10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8, 12. ,
       12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. , 14.2,
       14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2, 16.4,
       16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4, 18.6,
       18.8, 19. , 19.2, 19.4, 19.6, 19.8])

In [26]:
# equal division
a = np.linspace(0,10,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
a = np.array([1,2,3])
b = np.array([3,4,5])
print(a+b)

[4 6 8]


In [28]:
print(a-b)

[-2 -2 -2]


In [29]:
print(a*b)

[ 3  8 15]


In [30]:
liste = [1,2,3,4,5]
array = np.array([6,7,8,9,0])
print(f'liste = {liste}, array = {array}')

liste = [1, 2, 3, 4, 5], array = [6 7 8 9 0]


In [31]:
array = np.array(liste)
array

array([1, 2, 3, 4, 5])

In [42]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [40]:
b = a
c = a
b[0]=5
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [43]:
d = a.copy()
d

array([1, 2, 3])

In [44]:
a[0]=5

In [45]:
d

array([1, 2, 3])

In [46]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [47]:
print(a[0])

1


In [48]:
# up to 4 but not including
print(a[0:4])

[1 2 3 4]


In [49]:
a[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [54]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [55]:
b[1,1]

7

In [56]:
b[:,1]

array([2, 7])

In [61]:
print(b[1,:])

[ 6  7  8  9 10]


In [62]:
b[1,1:4]

array([7, 8, 9])

In [63]:
b[-1,:]

array([ 6,  7,  8,  9, 10])

In [64]:
b[:,-1]

array([ 5, 10])

In [66]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
b = x.ravel()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
b.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
b.resize(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])